version: '3.4'

services:
  web:
    env_file:
      - app/env-file
    container_name: twtraders
    image: localhost:5000/twtraders:latest
    # build:
    #   context: app
    #   dockerfile: Dockerfile
    ports:
      - "8080:80"